name: My New Job
description: This is my new Job

on: [push]

jobs: 
  test_build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
